import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div style={{ marginRight: "5%" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  );
}
